Tslint
afranco7/protractor-workshop-2017 pull request #7
Opened 2017-10-07 02:27 UTC by afranco7

2017-10-07 12:53 UTC, aperdomob requested changes

2017-10-07 12:53 UTC, aperdomob commented on package.json
> +    "tslint": "^5.7.0",
estos deberían ser dev-dependencies

2017-10-09 19:54 UTC, afranco7 commented on package.json
> +    "tslint": "^5.7.0",
Done.

2017-10-09 20:28 UTC, aperdomob requested changes

2017-10-09 20:28 UTC, aperdomob commented on protractor/headless.conf.ts
> +  framework: 'jasmine',
en este archivo te falta el SELENIUM_PROMISE_MANAGER

2017-10-09 20:36 UTC, afranco7 commented on protractor/headless.conf.ts
> +  framework: 'jasmine',
done..

2017-10-09 21:21 UTC, aperdomob approved these changes

2017-10-09 21:22 UTC, merged