adding all the page objects
afranco7/protractor-workshop-2017 pull request #9
Opened 2017-10-10 21:44 UTC by afranco7

2017-10-10 21:49 UTC, aperdomob requested changes

2017-10-10 21:49 UTC, aperdomob commented on src/page/ProductList.page.ts
> +  private get product(): ElementFinder {
agregar el sufijo Button

2017-10-10 21:49 UTC, aperdomob commented on test/BuyTshirt.spec.ts
> -    await(browser.sleep(10000));
este 10000 deberia quedar

2017-10-11 16:47 UTC, afranco7 commented on test/BuyTshirt.spec.ts
> -    await(browser.sleep(10000));
done

2017-10-11 16:52 UTC, aperdomob approved these changes

2017-10-11 16:53 UTC, merged